import './globals.css'
import Navbar from '@/components/Nav'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className='bg-gradient-to-r from-rose-100 to-teal-100'>
        <div className='main'></div>

        
        <div className='app '>
<Navbar />
          {children}
        </div>



        
        </body>
    </html>
  )
}
