import './globals.css'
import Navbar from '@/components/Nav'
import { UserAuth,AuthContextProvider } from '../context/AuthContext';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className='bg-gradient-to-r from-rose-100 to-teal-100'>
      <AuthContextProvider>

      <div className='main'></div>

        
<div className='app '>
<Navbar />
  {children}
</div>


      </AuthContextProvider>



        
        </body>
    </html>
  )
}
